routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages/home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('brand', 'BrandController');
Route::resource('category', 'CategoryController');
Route::resource('color', 'ColorController');
Route::resource('product', 'ProductController');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\Modifier;

class Product extends Model
{
    use Modifier;
    protected $fillable = [
        "name",
        "brand_id",
        "sku",
        "price",
        "description",
        "is_displayed",
        "start_promo",
        "end_promo",
        "promo_price",
        "gender",
        "material_upper",
        "material_outer_sole",
        "care_label",
        "measurement",
        "final_price"
    ];

    public function brand(){
        return $this->belongsTo("App\Brand");
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Brand;
use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->wantsJson()) {
            return datatables(Product::with('brand'))->toJson();
        } else {
            return view('pages.product.index');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $brands = Brand::get();
        return view('pages.product.create', ['brands' => $brands]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $payload = $request->all();
        Product::create($payload);
        return redirect()->route('product.create')->with('status', 'Data successfully created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::findOrFail($id);
        return view('pages.product.show', ['product' => $product]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::findOrFail($id);
        $brands = Brand::get();
        return view('pages.product.edit', ['product' => $product, 'brands' => $brands]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $payload = $request->all();
        $product = Product::findOrFail($id);
        $product->update($payload);

        return redirect()->route('product.edit', [$id])->with('status', 'Data successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::findOrFail($id);
        $product->delete();

        return redirect()->route('product.index')->with('status', 'Data successfully deleted');
    }
}

resources/views/pages/product/create.blade.php
@extends('layouts.default')

@section('title', 'Form Elements')

@push('css')
<script src='/assets/plugins/tinymce/tinymce.min.js' referrerpolicy="origin"></script>
@endpush

@section('content')

<!-- begin row -->
<div class="row">
    <!-- begin col-6 -->
    <div class="col-xl-12">
        <!-- begin panel -->
        <div class="panel panel-inverse" data-sortable-id="form-stuff-10">
            <!-- begin panel-heading -->
            <div class="panel-heading">
                <h4 class="panel-title">Create Product</h4>
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>
            </div>
            <!-- end panel-heading -->
            <!-- begin panel-body -->
            <div class="panel-body">
                @if(session('status'))
                <div class="alert alert-success">
                    {{session('status')}}
                </div>
                @endif
                <form action="{{route('product.store')}}" method="POST" enctype="multipart/form-data">
                    <fieldset>
                        @csrf
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="name" required />
                        </div>
                        <div class="form-group">
                            <label>Brand</label>
                            <select name="brand_id" class="form-control" id="brand_id">
                                <option></option>
                                @foreach($brands as $brand)
                                <option value="{{ $brand->id }}">{{ $brand->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label>SKU</label>
                            <input type="text" name="sku" class="form-control" id="sku" placeholder="sku" required />
                        </div>
                        <div class="form-group">
                            <label>Price</label>
                            <input type="number" name="price" class="form-control" id="price" required />
                        </div>
                        <div class="form-group">
                            <label>Description</label>
                            <textarea id="description" name="description" rows="20"></textarea>
                        </div>
                        <div class="form-group">
                            <label>Display</label>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" name="is_displayed" id="is_displayed" value="1" checked>
                                <label class="form-check-label" for="defaultRadio"></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Start Promo</label>
                            <input type="date" name="start_promo" class="form-control" id="start_promo" />
                        </div>
                        <div class="form-group">
                            <label>End Promo</label>
                            <input type="date" name="end_promo" class="form-control" id="end_promo" />
                        </div>
                        <div class="form-group">
                            <label>Promo Price</label>
                            <input type="number" name="promo_price" class="form-control" id="promo_price" />
                        </div>
                        <div class="form-group">
                            <label>Gender</label>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="gender" id="gender" value="Men">
                                <label class="form-check-label" for="defaultRadio">Men</label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="gender" id="gender" value="Women">
                                <label class="form-check-label" for="defaultRadio">Women</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Material Upper</label>
                            <input type="text" name="material_upper" class="form-control" id="material_upper" />
                        </div>
                        <div class="form-group">
                            <label>Material Outer Sole</label>
                            <input type="text" name="material_outer_sole" class="form-control" id="material_outer_sole" />
                        </div>
                        <div class="form-group">
                            <label>Care Label</label>
                            <textarea id="care_label" name="care_label" rows="20"></textarea>
                        </div>
                        <div class="form-group">
                            <label>Measurement</label>
                            <textarea id="measurement" name="measurement" rows="20"></textarea>
                        </div>
                        <div class="form-group">
                            <label>Final Price</label>
                            <input type="number" name="final_price" class="form-control" id="final_price" />
                        </div>
                        <button type="submit" class="btn btn-sm btn-primary m-r-5">Save</button>
                    </fieldset>
                </form>
            </div>
            <!-- end panel-body -->
        </div>
        <!-- end panel -->
    </div>
</div>
<!-- end row -->
@endsection

@push('scripts')
<script src="/assets/plugins/highlight.js/highlight.min.js"></script>
<script src="/assets/js/demo/render.highlight.js"></script>
<script type="text/javascript">
    tinymce.init({
        selector: '#description'
    });
    tinymce.init({
        selector: '#care_label'
    });
    tinymce.init({
        selector: '#measurement'
    });
</script>
@endpush

resources/views/pages/product/edit.blade.php
@extends('layouts.default')

@section('title', 'Form Elements')

@push('css')
<script src='/assets/plugins/tinymce/tinymce.min.js' referrerpolicy="origin"></script>
@endpush

@section('content')

<!-- begin row -->
<div class="row">
    <!-- begin col-6 -->
    <div class="col-xl-12">
        <!-- begin panel -->
        <div class="panel panel-inverse" data-sortable-id="form-stuff-10">
            <!-- begin panel-heading -->
            <div class="panel-heading">
                <h4 class="panel-title">Edit Product</h4>
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>
            </div>
            <!-- end panel-heading -->
            <!-- begin panel-body -->
            <div class="panel-body">
                @if(session('status'))
                <div class="alert alert-success">
                    {{session('status')}}
                </div>
                @endif
                <form action="{{route('product.update', [$product->id])}}" method="POST" enctype="multipart/form-data">
                    <fieldset>
                        @csrf
                        <input type="hidden" value="PUT" name="_method">
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="name" value="{{$product->name}}" required />
                        </div>
                        <div class="form-group">
                            <label>Brand</label>
                            <select name="brand_id" class="form-control" id="brand_id">
                                <option></option>
                                @foreach($brands as $brand)
                                <option value="{{ $brand->id }}" {{$product->brand_id == $brand->id ? 'selected' : ''}}>{{ $brand->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label>SKU</label>
                            <input type="text" name="sku" class="form-control" id="sku" placeholder="sku" value="{{$product->sku}}" required />
                        </div>
                        <div class="form-group">
                            <label>Price</label>
                            <input type="number" name="price" class="form-control" id="price" value="{{$product->price}}" required />
                        </div>
                        <div class="form-group">
                            <label>Description</label>
                            <textarea id="description" name="description" rows="20">{{$product->description}}</textarea>
                        </div>
                        <div class="form-group">
                            <label>Display</label>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" name="is_displayed" id="is_displayed" value="1" {{$product->is_displayed == '1' ? 'checked' : ''}}>
                                <label class="form-check-label" for="defaultRadio"></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Start Promo</label>
                            <input type="date" name="start_promo" class="form-control" id="start_promo" value="{{$product->start_promo}}" />
                        </div>
                        <div class="form-group">
                            <label>End Promo</label>
                            <input type="date" name="end_promo" class="form-control" id="end_promo" value="{{$product->end_promo}}" />
                        </div>
                        <div class="form-group">
                            <label>Promo Price</label>
                            <input type="number" name="promo_price" class="form-control" id="promo_price" value="{{$product->promo_price}}" />
                        </div>
                        <div class="form-group">
                            <label>Gender</label>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="gender" id="gender" value="Men" {{$product->gender == 'Men' ? 'checked' : ''}}>
                                <label class="form-check-label" for="defaultRadio">Men</label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="gender" id="gender" value="Women" {{$product->gender == 'Women' ? 'checked' : ''}}>
                                <label class="form-check-label" for="defaultRadio">Women</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Material Upper</label>
                            <input type="text" name="material_upper" class="form-control" id="material_upper" value="{{$product->material_upper}}" />
                        </div>
                        <div class="form-group">
                            <label>Material Outer Sole</label>
                            <input type="text" name="material_outer_sole" class="form-control" id="material_outer_sole" value="{{$product->material_outer_sole}}" />
                        </div>
                        <div class="form-group">
                            <label>Care Label</label>
                            <textarea id="care_label" name="care_label" rows="20">{{$product->care_label}}</textarea>
                        </div>
                        <div class="form-group">
                            <label>Measurement</label>
                            <textarea id="measurement" name="measurement" rows="20">{{$product->measurement}}</textarea>
                        </div>
                        <div class="form-group">
                            <label>Final Price</label>
                            <input type="number" name="final_price" class="form-control" id="final_price" value="{{$product->final_price}}" />
                        </div>
                        <button type="submit" class="btn btn-sm btn-primary m-r-5">Update</button>
                    </fieldset>
                </form>
            </div>
            <!-- end panel-body -->
        </div>
        <!-- end panel -->
    </div>
</div>
<!-- end row -->
@endsection

@push('scripts')
<script src="/assets/plugins/highlight.js/highlight.min.js"></script>
<script src="/assets/js/demo/render.highlight.js"></script>
<script type="text/javascript">
    tinymce.init({
        selector: '#description'
    });
    tinymce.init({
        selector: '#care_label'
    });
    tinymce.init({
        selector: '#measurement'
    });
</script>
@endpush

resources/views/pages/product/index.blade.php
@extends('layouts.default')

@section('title', 'Managed Tables')

@push('css')
<link href="/assets/plugins/datatables.net-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<link href="/assets/plugins/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css" rel="stylesheet" />
@endpush

@section('content')

<!-- begin panel -->
<div class="panel panel-inverse">
    <!-- begin panel-heading -->
    <div class="panel-heading">
        <h4 class="panel-title">Product</h4>
        <div class="panel-heading-btn">
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
        </div>
    </div>
    <!-- end panel-heading -->
    <!-- begin panel-body -->
    <div class="panel-body">
        <a href="{{route('product.create')}}" type="button" class="btn btn-primary">Create</a>
        <table id="data-table" class="table table-striped table-bordered table-td-valign-middle">
            <thead>
                <tr>
                    <th width="1%"></th>
                    <th class="text-nowrap">Name</th>
                    <th class="text-nowrap">Brand</th>
                    <th class="text-nowrap">SKU</th>
                    <th class="text-nowrap">Price</th>
                    <th class="text-nowrap">Images</th>
                    <th class="text-nowrap">Variants & Stock</th>
                    <th class="text-nowrap"></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
    <!-- end panel-body -->
</div>
<!-- end panel -->
@endsection

@push('scripts')
<script src="/assets/plugins/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/assets/plugins/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="/assets/plugins/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
<script src="/assets/plugins/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js"></script>
<script>
    var datatable;
    $(document).ready(function() {
        datatable = $('#data-table').DataTable({
            serverSide: true,
            processing: true,
            ajax: "{{route('product.index')}}",
            columns: [{
                data: 'id',
                render: function(data, type, row, attr) {
                    return attr.row + attr.settings._iDisplayStart + 1;
                },
                searchable: false,
                orderable: false
            }, {
                data: 'name'
            }, {
                data: 'brand.name'
            }, {
                data: 'sku'
            }, {
                data: 'price'
            }, {
                data: null,
                searchable: false,
                orderable: false,
            }, {
                data: null,
                searchable: false,
                orderable: false,
            }, {
                data: null,
                searchable: false,
                orderable: false,
                render: function(r, v, i) {
                    return `
                                <a href="{{route('product.index')}}/${r.id}" class="btn btn-info btn-xs"><i class="fa fa-info-circle"></i></a>&nbsp;
                                <a href="{{route('product.index')}}/${r.id}/edit" class="btn btn-warning btn-xs"><i class="fa fa-edit"></i></a>&nbsp;
                                <form class="d-inline" action="{{route('product.index')}}/${r.id}" method="POST" onsubmit="return confirm('Move data to trash?')">
                                    @csrf 
                                    <input type="hidden" value="DELETE" name="_method">
                                    <button type="submit" class="btn btn-danger btn-xs"><i class="fa fa-trash"></i></button>
                                </form>
                        `;
                }
            }]
        });
    });
</script>
@endpush

resources/views/pages/product/show.blade.php
@extends('layouts.default')

@section('title', 'Form Elements')

@push('css')
<script src='/assets/plugins/tinymce/tinymce.min.js' referrerpolicy="origin"></script>
@endpush

@section('content')

<!-- begin row -->
<div class="row">
    <!-- begin col-6 -->
    <div class="col-xl-12">
        <!-- begin panel -->
        <div class="panel panel-inverse" data-sortable-id="form-stuff-10">
            <!-- begin panel-heading -->
            <div class="panel-heading">
                <h4 class="panel-title">Detail Product</h4>
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>
            </div>
            <!-- end panel-heading -->
            <!-- begin panel-body -->
            <div class="panel-body">
                @if(session('status'))
                <div class="alert alert-success">
                    {{session('status')}}
                </div>
                @endif
                <form>
                    <fieldset>
                        @csrf
                        <input type="hidden" value="PUT" name="_method">
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="name" value="{{$product->name}}" disabled />
                        </div>
                        <div class="form-group">
                            <label>Brand</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="name" value="{{$product->brand->name}}" disabled />
                        </div>
                        <div class="form-group">
                            <label>SKU</label>
                            <input type="text" name="sku" class="form-control" id="sku" placeholder="sku" value="{{$product->sku}}" disabled />
                        </div>
                        <div class="form-group">
                            <label>Price</label>
                            <input type="number" name="price" class="form-control" id="price" value="{{$product->price}}" disabled />
                        </div>
                        <div class="form-group">
                            <label>Description</label>
                            <textarea id="description" name="description" rows="20" disabled>{{$product->description}}</textarea>
                        </div>
                        <div class="form-group">
                            <label>Display</label>
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" name="is_displayed" id="is_displayed" value="1" disabled {{$product->is_displayed == '1' ? 'checked' : ''}}>
                                <label class="form-check-label" for="defaultRadio"></label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Start Promo</label>
                            <input type="date" name="start_promo" class="form-control" id="start_promo" value="{{$product->start_promo}}" disabled/>
                        </div>
                        <div class="form-group">
                            <label>End Promo</label>
                            <input type="date" name="end_promo" class="form-control" id="end_promo" value="{{$product->end_promo}}" disabled/>
                        </div>
                        <div class="form-group">
                            <label>Promo Price</label>
                            <input type="number" name="promo_price" class="form-control" id="promo_price" value="{{$product->promo_price}}" disabled/>
                        </div>
                        <div class="form-group">
                            <label>Gender</label>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="gender" id="gender" value="Men" disabled {{$product->gender == 'Men' ? 'checked' : ''}}>
                                <label class="form-check-label" for="defaultRadio">Men</label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="gender" id="gender" value="Women" disabled {{$product->gender == 'Women' ? 'checked' : ''}}>
                                <label class="form-check-label" for="defaultRadio">Women</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Material Upper</label>
                            <input type="text" name="material_upper" class="form-control" id="material_upper" value="{{$product->material_upper}}" disabled />
                        </div>
                        <div class="form-group">
                            <label>Material Outer Sole</label>
                            <input type="text" name="material_outer_sole" class="form-control" id="material_outer_sole" value="{{$product->material_outer_sole}}" disabled />
                        </div>
                        <div class="form-group">
                            <label>Care Label</label>
                            <textarea id="care_label" name="care_label" rows="20">{{$product->care_label}}</textarea>
                        </div>
                        <div class="form-group">
                            <label>Measurement</label>
                            <textarea id="measurement" name="measurement" rows="20">{{$product->measurement}}</textarea>
                        </div>
                        <div class="form-group">
                            <label>Final Price</label>
                            <input type="number" name="final_price" class="form-control" id="final_price" value="{{$product->final_price}}" disabled />
                        </div>
                    </fieldset>
                </form>
            </div>
            <!-- end panel-body -->
        </div>
        <!-- end panel -->
    </div>
</div>
<!-- end row -->
@endsection

@push('scripts')
<script src="/assets/plugins/highlight.js/highlight.min.js"></script>
<script src="/assets/js/demo/render.highlight.js"></script>
<script type="text/javascript">
    tinymce.init({
        selector: '#description',
        readonly : 1
    });
    tinymce.init({
        selector: '#care_label',
        readonly : 1
    });
    tinymce.init({
        selector: '#measurement',
        readonly : 1
    });
</script>
@endpush