routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('pages/home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('brand', 'BrandController');
Route::resource('category', 'CategoryController');
Route::resource('color', 'ColorController');
Route::resource('product', 'ProductController');

app/Color.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\Modifier;

class Color extends Model
{
    use Modifier;
    protected $fillable = ["name", "rgb"];
}

app/Http/Controllers/ColorController.php
<?php

namespace App\Http\Controllers;

use App\Color;
use Illuminate\Http\Request;

class ColorController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->wantsJson()) {
            return datatables(Color::query())->toJson();
        } else {
            return view('pages.color.index');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.color.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $payload = $request->all();
        Color::create($payload);
        return redirect()->route('color.create')->with('status', 'Data successfully created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $color = Color::findOrFail($id);
        return view('pages.color.edit', ['color' => $color]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $payload = $request->only("name", "rgb");
        $color = Color::findOrFail($id);
        $color->update($payload);

        return redirect()->route('color.edit', [$id])->with('status', 'Data successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $color = Color::findOrFail($id);
        $color->delete();

        return redirect()->route('color.index')->with('status', 'Data successfully deleted');
    }
}

resources/views/pages/color/create.blade.php
@extends('layouts.default')

@section('title', 'Form Elements')

@section('content')

<!-- begin row -->
<div class="row">
    <!-- begin col-6 -->
    <div class="col-xl-12">
        <!-- begin panel -->
        <div class="panel panel-inverse" data-sortable-id="form-stuff-10">
            <!-- begin panel-heading -->
            <div class="panel-heading">
                <h4 class="panel-title">Create Color</h4>
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>
            </div>
            <!-- end panel-heading -->
            <!-- begin panel-body -->
            <div class="panel-body">
                @if(session('status'))
                <div class="alert alert-success">
                    {{session('status')}}
                </div>
                @endif
                <form action="{{route('color.store')}}" method="POST" enctype="multipart/form-data">
                    <fieldset>
                        @csrf
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="name" required/>
                        </div>
                        <div class="form-group">
                            <label>RGB</label>
                            <input type="text" name="rgb" class="form-control" id="rgb" placeholder="rgb" required/>
                        </div>
                        <button type="submit" class="btn btn-sm btn-primary m-r-5">Save</button>
                    </fieldset>
                </form>
            </div>
            <!-- end panel-body -->
        </div>
        <!-- end panel -->
    </div>
</div>
<!-- end row -->
@endsection

@push('scripts')
<script src="/assets/plugins/highlight.js/highlight.min.js"></script>
<script src="/assets/js/demo/render.highlight.js"></script>
@endpush

resources/views/pages/color/edit.blade.php
@extends('layouts.default')

@section('title', 'Form Elements')

@section('content')

<!-- begin row -->
<div class="row">
    <!-- begin col-6 -->
    <div class="col-xl-12">
        <!-- begin panel -->
        <div class="panel panel-inverse" data-sortable-id="form-stuff-10">
            <!-- begin panel-heading -->
            <div class="panel-heading">
                <h4 class="panel-title">Edit Color</h4>
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>
            </div>
            <!-- end panel-heading -->
            <!-- begin panel-body -->
            <div class="panel-body">
                @if(session('status'))
                <div class="alert alert-success">
                    {{session('status')}}
                </div>
                @endif
                <form action="{{route('color.update', [$color->id])}}" method="POST" enctype="multipart/form-data">
                    <fieldset>
                        @csrf
                        <input type="hidden" value="PUT" name="_method">
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="name" value="{{$color->name}}" required/>
                        </div>
                        <div class="form-group">
                            <label>RGB</label>
                            <input type="text" name="rgb" class="form-control" id="rgb" placeholder="name" value="{{$color->rgb}}" required/>
                        </div>
                        <button type="submit" class="btn btn-sm btn-primary m-r-5">Update</button>
                    </fieldset>
                </form>
            </div>
            <!-- end panel-body -->
        </div>
        <!-- end panel -->
    </div>
</div>
<!-- end row -->
@endsection

@push('scripts')
<script src="/assets/plugins/highlight.js/highlight.min.js"></script>
<script src="/assets/js/demo/render.highlight.js"></script>
@endpush

resources/views/pages/color/index.blade.php
@extends('layouts.default')

@section('title', 'Managed Tables')

@push('css')
<link href="/assets/plugins/datatables.net-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<link href="/assets/plugins/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css" rel="stylesheet" />
@endpush

@section('content')

<!-- begin panel -->
<div class="panel panel-inverse">
    <!-- begin panel-heading -->
    <div class="panel-heading">
        <h4 class="panel-title">Color</h4>
        <div class="panel-heading-btn">
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
        </div>
    </div>
    <!-- end panel-heading -->
    <!-- begin panel-body -->
    <div class="panel-body">
        <a href="{{route('color.create')}}" type="button" class="btn btn-primary">Create</a>
        <table id="data-table" class="table table-striped table-bordered table-td-valign-middle">
            <thead>
                <tr>
                    <th width="1%"></th>
                    <th class="text-nowrap">Name</th>
                    <th class="text-nowrap">RGB</th>
                    <th class="text-nowrap"></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
    <!-- end panel-body -->
</div>
<!-- end panel -->
@endsection

@push('scripts')
<script src="/assets/plugins/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/assets/plugins/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="/assets/plugins/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
<script src="/assets/plugins/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js"></script>
<script>
    var datatable;
    $(document).ready(function() {
        datatable = $('#data-table').DataTable({
            serverSide: true,
            processing: true,
            ajax: "{{route('color.index')}}",
            columns: [{
                data: 'id',
                render: function(data, type, row, attr) {
                    return attr.row + attr.settings._iDisplayStart + 1;
                },
                searchable: false,
                orderable: false
            }, {
                data: 'name'
            }, {
                data: 'rgb'
            }, {
                data: null,
                searchable: false,
                orderable: false,
                render: function(r, v, i) {
                    return `
                                <a href="{{route('color.index')}}/${r.id}/edit" class="btn btn-warning btn-xs"><i class="fa fa-edit"></i></a>&nbsp;
                                <form class="d-inline" action="{{route('color.index')}}/${r.id}" method="POST" onsubmit="return confirm('Move data to trash?')">
                                    @csrf 
                                    <input type="hidden" value="DELETE" name="_method">
                                    <button type="submit" class="btn btn-danger btn-xs"><i class="fa fa-trash"></i></button>
                                </form>
                        `;
                }
            }]
        });
    });
</script>
@endpush